self.__uv$config = {
    prefix: '/active/go/',
    bare: '/bare/',
    encodeUrl: Ultraviolet.codec.plain.encode,
    decodeUrl: Ultraviolet.codec.plain.decode,
    handler: '/active/uv/uv.handler.js',
    bundle: '/active/uv/uv.bundle.js',
    config: '/active/uv/uv.config.js',
    sw: '/active/uv/uv.sw.js',
    inject: true,
    rewriteUrl: true,
    cors: true,
    cookies: true,
    referer: true,
    cache: true,
    aggressiveCache: true,
    optimizeScripts: true,
    optimizeStyles: true,
    debug: false,
    logLevel: 0,
};
